use quanlychungcu
psHienThiHoaDonVaChiTietDichVu

create proc psHienThiHoaDonVaChiTietDichVu
as
begin transaction
	select  HOADONDICHVU.MAHOADONDV, TENHOADON, DICHVU.MADICHVU, SOLUONG, DONGIA, MANHANVIEN, MAHOGD, MACANHO, NGAYIN, SOLUONG*DONGIA AS THANHTIEN, HOADONDICHVU.GHICHU
	FROM HOADONDICHVU, CTHDDICHVU, DICHVU
	WHERE DICHVU.MADICHVU = CTHDDICHVU.MADICHVU AND HOADONDICHVU.MAHOADONDV =  CTHDDICHVU.MAHOADONDV
if (@@ERROR <> 0)
ROLLBACK TRANSACTION
else
COMMIT TRANSACTION


create procedure psHienThiHoaDonDichVu
as
begin transaction
	select * from HOADONDICHVU
if (@@ERROR <> 0)
ROLLBACK TRANSACTION
else
COMMIT TRANSACTION


create procedure psHienThiDichVu
as
begin transaction
	select * from DICHVU
if (@@ERROR <> 0)
ROLLBACK TRANSACTION
else
COMMIT TRANSACTION


CREATE procedure psThemHoaDonDichVu @MAHOADONDV NVARCHAR(10), 
	@TENHOADON NVARCHAR(30), 
	@MANHANVIEN NVARCHAR(10),
	@MAHOGD NVARCHAR(10), 
	@MACANHO NVARCHAR(10), 
	@NGAYIN DATETIME, 
	@TONGTIEN FLOAT,
	@GHICHU NVARCHAR(30)
as
begin transaction
if exists (select * from HOADONDICHVU where MAHOADONDV = @MAHOADONDV)
		return
else
		insert into HOADONDICHVU values (@MAHOADONDV, @TENHOADON,@MANHANVIEN,@MAHOGD,@MACANHO,@NGAYIN,@TONGTIEN,@GHICHU)
if (@@ERROR <> 0)
ROLLBACK TRANSACTION
else
COMMIT TRANSACTION



create proc psXoaHoaDonDichVu @MAHOADONDV NVARCHAR (10)
as
begin transaction
		delete from HOADONDICHVU where MAHOADONDV = @MAHOADONDV
if (@@ERROR <> 0)
ROLLBACK TRANSACTION
else
COMMIT TRANSACTION


create procedure psSuaHoaDonDichVu @MAHOADONDV NVARCHAR(10), 
	@TENHOADON NVARCHAR(30), 
	@MANHANVIEN NVARCHAR(10),
	@MAHOGD NVARCHAR(10), 
	@MACANHO NVARCHAR(10), 
	@NGAYIN DATETIME, 
	@TONGTIEN FLOAT,
	@GHICHU NVARCHAR(30)
as
begin transaction
	if not exists (select * from HOADONDICHVU where MAHOADONDV = @MAHOADONDV)
		return
	else
		update HOADONDICHVU set TENHOADON=@TENHOADON, MANHANVIEN=@MANHANVIEN, MAHOGD=@MAHOGD, MACANHO=@MACANHO, NGAYIN=@NGAYIN, TONGTIEN=@TONGTIEN, GHICHU=@GHICHU
							where MAHOADONDV = @MAHOADONDV
if (@@ERROR <> 0)
ROLLBACK TRANSACTION
else
COMMIT TRANSACTION




CREATE procedure psThemChiTietHoaDonDichVu @MAHOADONDV NVARCHAR(10),
 @SOLUONG INT, 
 @DONGIA FLOAT, 
 @GHICHU NVARCHAR(50), 
 @MADICHVU NVARCHAR(10)
as
begin transaction
		insert into CTHDDICHVU values (@MAHOADONDV, @SOLUONG, @DONGIA, @GHICHU, @MADICHVU)
if (@@ERROR <> 0)
ROLLBACK TRANSACTION
else
COMMIT TRANSACTION



create procedure psSuaChiTietHoaDonDichVu @MAHOADONDV NVARCHAR(10),
 @SOLUONG INT, 
 @DONGIA FLOAT, 
 @GHICHU NVARCHAR(50), 
 @MADICHVU NVARCHAR(10)
as
begin transaction
	if not exists (select * from CTHDDICHVU where MAHOADONDV = @MAHOADONDV)
		return
	else
		update CTHDDICHVU set SOLUONG=@SOLUONG,GHICHU=@GHICHU where MAHOADONDV = @MAHOADONDV
if (@@ERROR <> 0)
ROLLBACK TRANSACTION
else
COMMIT TRANSACTION


create proc psXoaChiTietHoaDonDichVu @MAHOADONDV NVARCHAR (10)
as
begin transaction
		delete from CTHDDICHVU where MAHOADONDV = @MAHOADONDV	
if (@@ERROR <> 0)
ROLLBACK TRANSACTION
else
COMMIT TRANSACTION


create procedure psThemTongTienChoHoaDonDichVu
    @MAHOADONDV NVARCHAR (10),
    @TONGTIEN       FLOAT
as
begin transaction
		update HOADONDICHVU set TONGTIEN=@TONGTIEN where MAHOADONDV = @MAHOADONDV	
if (@@ERROR <> 0)
ROLLBACK TRANSACTION
else
COMMIT TRANSACTION



create procedure psTimKiemHoaDonDichVuTheoMaHoaDon @MAHOADONDV nvarchar(10)
as
begin transaction
	select * from HOADONDICHVU where MAHOADONDV = @MAHOADONDV	
if (@@ERROR <> 0)
ROLLBACK TRANSACTION
else
COMMIT TRANSACTION

create proc psHienThiHoaDonVaChiTietDichVuTheoMaHoaDon @MAHOADONDV nvarchar(10)
as
begin transaction
	select  HOADONDICHVU.MAHOADONDV, TENHOADON, DICHVU.MADICHVU, SOLUONG, DONGIA, MANHANVIEN, MAHOGD, MACANHO, NGAYIN, SOLUONG*DONGIA AS THANHTIEN, HOADONDICHVU.GHICHU
	FROM HOADONDICHVU, CTHDDICHVU, DICHVU
	WHERE DICHVU.MADICHVU = CTHDDICHVU.MADICHVU AND HOADONDICHVU.MAHOADONDV =  CTHDDICHVU.MAHOADONDV and HOADONDICHVU.MAHOADONDV = @MAHOADONDV
if (@@ERROR <> 0)
ROLLBACK TRANSACTION
else
COMMIT TRANSACTION