USE quanlychungcu

CREATE PROCEDURE psThemThanhVienHoGD  @MATHANHVIEN NVARCHAR (10), @HOTENTHANHVIEN NVARCHAR (30), 
								@GIOITINHTV NVARCHAR (10), @SOCMND NVARCHAR (18), @NGAYSINH date, @SDT NVARCHAR (10), 
								@EMAIL NVARCHAR (30), @HINHANH IMAGE, @MAHOGD NVARCHAR (10)
AS
BEGIN TRANSACTION
	IF EXISTS (Select * from THANHVIENHOGD where MATHANHVIEN = @MATHANHVIEN)
		RETURN
	ELSE
		INSERT INTO THANHVIENHOGD VALUES (@MATHANHVIEN,@HOTENTHANHVIEN,@GIOITINHTV,@SOCMND,@NGAYSINH, @SDT,@EMAIL,@HINHANH,@MAHOGD)
if (@@ERROR <> 0)
ROLLBACK TRANSACTION
else
COMMIT TRANSACTION

EXEC psThemThanhVienHoGD '1', 'A','Nữ','123','1/4/1999','1234','AAAA',NULL,'HGD1'

CREATE PROCEDURE psXoaThanhVienHoGD @MATHANHVIEN NVARCHAR (10)
AS
BEGIN TRANSACTION
	IF NOT EXISTS (Select * from THANHVIENHOGD where MATHANHVIEN = @MATHANHVIEN)
		RETURN
	ELSE
		DELETE FROM THANHVIENHOGD WHERE MATHANHVIEN = @MATHANHVIEN
if (@@ERROR <> 0)
ROLLBACK TRANSACTION
else
COMMIT TRANSACTION


CREATE PROCEDURE psSuaThanhVienHoGD @MATHANHVIEN NVARCHAR (10), @HOTENTHANHVIEN NVARCHAR (30), 
										@GIOITINHTV NVARCHAR (10),@SOCMND NVARCHAR (18), @NGAYSINH DATE,
										 @SDT NVARCHAR (10), 
										@EMAIL NVARCHAR (30), @HINHANH IMAGE, @MAHOGD NVARCHAR (10)
AS
BEGIN TRANSACTION
	IF NOT EXISTS (Select * from THANHVIENHOGD where MATHANHVIEN = @MATHANHVIEN)
		RETURN
	ELSE
	   UPDATE THANHVIENHOGD SET HOTENTHANHVIEN = @HOTENTHANHVIEN, GIOITINHTV = @GIOITINHTV, SOCMND = @SOCMND, @NGAYSINH = @NGAYSINH,
								SDT = @SDT, EMAIL = @EMAIL, HINHANH = @HINHANH, MAHOGD = @MAHOGD WHERE MATHANHVIEN = @MATHANHVIEN 
if (@@ERROR <> 0)
ROLLBACK TRANSACTION
else
COMMIT TRANSACTION


CREATE PROCEDURE psTimThanhVien @MATHANHVIEN NVARCHAR (10)
AS
BEGIN TRANSACTION
	select *from THANHVIENHOGD WHERE MATHANHVIEN = @MATHANHVIEN
if (@@ERROR <> 0)
ROLLBACK TRANSACTION
else
COMMIT TRANSACTION



CREATE PROCEDURE psHIENTHITHANHVIENTHEOHO @MAHOGD NVARCHAR (10)
AS
BEGIN TRANSACTION
	select *from THANHVIENHOGD WHERE MAHOGD = @MAHOGD
if (@@ERROR <> 0)
ROLLBACK TRANSACTION
else
COMMIT TRANSACTION

exec psHIENTHITHANHVIENTHEOHO 'HGD1'


CREATE PROCEDURE psHienThiThanhVien 
AS
BEGIN TRANSACTION
	select * from THANHVIENHOGD 
if (@@ERROR <> 0)
ROLLBACK TRANSACTION
else
COMMIT TRANSACTION


CREATE TRIGGER ktraNhapTV on THANHVIENHOGD for INSERT AS
DECLARE @SoLuongTV  int
Declare @MaHoGD nvarchar (10) 
Select @SoLuongTV= SOLUONGTV, @MaHoGD = HOGIADINH.MAHOGD
From HOGIADINH, inserted
where HOGIADINH.MAHOGD = inserted.MAHOGD
Update HOGIADINH set SOLUONGTV = SOLUONGTV +1 where MAHOGD = @MaHoGD
return

CREATE TRIGGER ktraXoaThanhVien on THANHVIENHOGD for DELETE AS
DECLARE @SoLuongTV  int
Declare @MaHoGD nvarchar (10) 
Select @SoLuongTV= SOLUONGTV, @MaHoGD = HOGIADINH.MAHOGD
From HOGIADINH,  deleted
where HOGIADINH.MAHOGD = deleted.MAHOGD
Update HOGIADINH set SOLUONGTV = SOLUONGTV - 1 where MAHOGD = @MaHoGD
return

exec psHienThiThanhVien
select * from THANHVIENHOGD
exec psHienThiHoGiaDinh



