USE quanlychungcu
select * from HOADONNUOC
create proc psHienThiHoaDonVaChiTietHoaDonNuoc
as
begin transaction
	select HOADONNUOC.MAHOADONNUOC, TENHOADON, SOLUONG, DONGIA, MANHANVIEN, MAHOGD, MACANHO, NGAYIN, SOLUONG*DONGIA AS THANHTIEN, HOADONNUOC.GHICHU
	FROM HOADONNUOC, CTHDNUOC
	WHERE HOADONNUOC.MAHOADONNUOC=CTHDNUOC.MAHOADONNUOC
if (@@ERROR <> 0)
ROLLBACK TRANSACTION
else
COMMIT TRANSACTION

create procedure psHienThiHoaDonNuoc
as
begin transaction
	select * from HOADONNUOC
if (@@ERROR <> 0)
ROLLBACK TRANSACTION
else
COMMIT TRANSACTION

CREATE procedure psThemHoaDonNuoc
    @MAHOADONNUOC NVARCHAR (10),
    @TENHOADON   NVARCHAR (30),
    @MANHANVIEN   NVARCHAR (10),
    @MAHOGD       NVARCHAR (10),
    @MACANHO      NVARCHAR (10),
    @NGAYIN      DATETIME,
    @TONGTIEN    FLOAT,
    @GHICHU       NVARCHAR (50)
as
begin transaction
if exists (select * from HOADONNUOC where MAHOADONNUOC = @MAHOADONNUOC)
		return
else
		insert into HOADONNUOC values (@MAHOADONNUOC, @TENHOADON,@MANHANVIEN,@MAHOGD,@MACANHO,@NGAYIN,@TONGTIEN,@GHICHU)
if (@@ERROR <> 0)
ROLLBACK TRANSACTION
else
COMMIT TRANSACTION


create proc psXoaHoaDonNuoc @MAHOADONNUOC NVARCHAR (10)
as
begin transaction
		delete from HOADONNUOC where MAHOADONNUOC = @MAHOADONNUOC		
if (@@ERROR <> 0)
ROLLBACK TRANSACTION
else
COMMIT TRANSACTION


create procedure psSuaHoaDonNuoc (@MAHOADONNUOC NVARCHAR (10),
    @TENHOADON   NVARCHAR (30),
    @MANHANVIEN   NVARCHAR (10),
    @MAHOGD       NVARCHAR (10),
    @MACANHO      NVARCHAR (10),
    @NGAYIN      DATETIME,
    @TONGTIEN    FLOAT (53),
    @GHICHU       NVARCHAR (50))
as
begin transaction
	if not exists (select * from HOADONNUOC where MAHOADONNUOC = MAHOADONNUOC)
		return
	else
		update HOADONNUOC set TENHOADON=@TENHOADON, MANHANVIEN=@MANHANVIEN, MAHOGD=@MAHOGD, MACANHO=@MACANHO, NGAYIN=@NGAYIN, TONGTIEN=@TONGTIEN, GHICHU=@GHICHU
							where MAHOADONNUOC=MAHOADONNUOC
if (@@ERROR <> 0)
ROLLBACK TRANSACTION
else
COMMIT TRANSACTION



CREATE procedure psThemChiTietHoaDonNuoc
    @MAHOADONNUOC NVARCHAR (10),
    @SOLUONG      INT,
    @DONGIA       FLOAT,
    @GHICHU       NVARCHAR (50)
as
begin transaction
		insert into CTHDNUOC values (@MAHOADONNUOC, @SOLUONG, @DONGIA, @GHICHU)
if (@@ERROR <> 0)
ROLLBACK TRANSACTION
else
COMMIT TRANSACTION

create procedure psSuaChiTietHoaDonNuoc
    @MAHOADONNUOC NVARCHAR (10),
    @SOLUONG      INT,
    @GHICHU       NVARCHAR (50)
as
begin transaction
	if not exists (select * from CTHDNUOC where MAHOADONNUOC = @MAHOADONNUOC)
		return
	else
		update CTHDNUOC set SOLUONG=@SOLUONG,GHICHU=@GHICHU WHERE MAHOADONNUOC=@MAHOADONNUOC
if (@@ERROR <> 0)
ROLLBACK TRANSACTION
else
COMMIT TRANSACTION


create proc psXoaChiTietHoaDonNuoc @MAHOADONNUOC NVARCHAR (10)
as
begin transaction
		delete from CTHDNUOC where MAHOADONNUOC = @MAHOADONNUOC		
if (@@ERROR <> 0)
ROLLBACK TRANSACTION
else
COMMIT TRANSACTION



create procedure psThemTongTienChoHoaDonNuoc
    @MAHOADONNUOC NVARCHAR (10),
    @TONGTIEN       FLOAT
as
begin transaction
		update HOADONNUOC set TONGTIEN=@TONGTIEN where MAHOADONNUOC=@MAHOADONNUOC
if (@@ERROR <> 0)
ROLLBACK TRANSACTION
else
COMMIT TRANSACTION


create procedure psTimKiemChiTietHoaDonNuocTheoMaHoaDon @MAHOADONNUOC nvarchar(10)
as
begin transaction
	select * from CTHDNUOC where MAHOADONNUOC = @MAHOADONNUOC
if (@@ERROR <> 0)
ROLLBACK TRANSACTION
else
COMMIT TRANSACTION


create proc psHienThiHoaDonVaChiTietHoaDonNuocTheoMaHoaDon @MAHOADONNUOC nvarchar(10)
as
begin transaction
	select HOADONNUOC.MAHOADONNUOC, TENHOADON, SOLUONG, DONGIA, MANHANVIEN, MAHOGD, MACANHO, NGAYIN, SOLUONG*DONGIA AS THANHTIEN, HOADONNUOC.GHICHU
	FROM HOADONNUOC, CTHDNUOC
	WHERE HOADONNUOC.MAHOADONNUOC=CTHDNUOC.MAHOADONNUOC
	AND HOADONNUOC.MAHOADONNUOC=@MAHOADONNUOC
if (@@ERROR <> 0)
ROLLBACK TRANSACTION
else
COMMIT TRANSACTION