Use quanlychungcu


CREATE PROCEDURE psThemCanHo @MACANHO NVARCHAR (10), @TENCANHO NVARCHAR (20),@LOAICANHO NVARCHAR (10), @HINHANH IMAGE, @GIACANHO FLOAT, @TRANGTHAI NVARCHAR (30),@GHICHU NVARCHAR(50), @MAKHU NVARCHAR (10), @MAHOGD NVARCHAR(10)
AS
BEGIN TRANSACTION
	if exists (Select * from CANHO WHERE MACANHO = @MACANHO)
		return 
	else
		Insert into CANHO VALUES (@MACANHO,@TENCANHO, @LOAICANHO,@HINHANH,@GIACANHO,@TRANGTHAI,@GHICHU,@MAKHU,@MAHOGD)
if (@@ERROR <> 0)
ROLLBACK TRANSACTION
else
COMMIT TRANSACTION

insert into KHU values ('K1','Khu A')
insert into KHU values ('K2','Khu B')
insert into KHU values ('K3','Khu C')

create procedure psHienThiMaKhu 
As
begin transaction
	select * from KHU
if (@@ERROR <> 0)
ROLLBACK TRANSACTION
else
COMMIT TRANSACTION


CREATE PROCEDURE psXoaCanHo @MACANHO NVARCHAR (10)
AS
BEGIN TRANSACTION
	if exists (Select * from CANHO WHERE MACANHO = @MACANHO)
		DELETE FROM CANHO WHERE MACANHO = @MACANHO
	else
		PRINT 'KHONG CÓ CĂN HÔ NÀY'
		
if (@@ERROR <> 0)
ROLLBACK TRANSACTION
else
COMMIT TRANSACTION



CREATE PROCEDURE psSuaCanHo @MACANHO NVARCHAR (10), @TENCANHO NVARCHAR (20),@LOAICANHO NVARCHAR (10), 
								@HINHANH IMAGE, @GIACANHO FLOAT,
								@GHICHU NVARCHAR(50), @MAKHU NVARCHAR (10), @MAHOGD NVARCHAR(10)
AS
BEGIN TRANSACTION
	if not exists (Select * from CANHO WHERE MACANHO = @MACANHO)
		return 
	else
		update CANHO set TENCANHO = @TENCANHO, LOAICANHO = @LOAICANHO, HINHANH = @HINHANH, GIACANHO = @GIACANHO,
									  GHICHU = @GHICHU, 
									MAKHU = @MAKHU, MAHOGD = @MAHOGD WHERE MACANHO = @MACANHO
if (@@ERROR <> 0)
ROLLBACK TRANSACTION
else
COMMIT TRANSACTION


CREATE PROCEDURE psTimCanHo @MACANHO NVARCHAR (10)
AS
BEGIN TRANSACTION
	Select * from CANHO WHERE MACANHO = @MACANHO
if (@@ERROR <> 0)
ROLLBACK TRANSACTION
else
COMMIT TRANSACTION



CREATE PROCEDURE psHienThiCanHo 
AS
BEGIN TRANSACTION
	Select * from CANHO 
if (@@ERROR <> 0)
ROLLBACK TRANSACTION
else
COMMIT TRANSACTION



CREATE PROCEDURE psThemHoGiaDinh @MAHOGD NVARCHAR (10), @TENCHUHO NVARCHAR (30), @SOCMND NVARCHAR (18), @SOLUONGTV INT
AS
BEGIN TRANSACTION
	IF EXISTS (Select * from HOGIADINH where MAHOGD = @MAHOGD)
		RETURN
	ELSE
		INSERT INTO HOGIADINH VALUES (@MAHOGD,@TENCHUHO,@SOCMND,@SOLUONGTV)
if (@@ERROR <> 0)
ROLLBACK TRANSACTION
else
COMMIT TRANSACTION

select * from HOGIADINH



CREATE PROCEDURE psXoaHoGiaDinh @MAHOGD NVARCHAR (10)
AS
BEGIN TRANSACTION
	IF not EXISTS (Select * from HOGIADINH where MAHOGD = @MAHOGD)
		RETURN
	ELSE
		DELETE FROM  HOGIADINH WHERE MAHOGD = @MAHOGD
if (@@ERROR <> 0)
ROLLBACK TRANSACTION
else
COMMIT TRANSACTION



CREATE PROCEDURE psSuaHoGiaDinh @MAHOGD NVARCHAR (10), @TENCHUHO NVARCHAR (30), @SOCMND NVARCHAR (18), @SOLUONGTV INT
AS
BEGIN TRANSACTION
	IF not EXISTS (Select * from HOGIADINH where MAHOGD = @MAHOGD)
		RETURN
	ELSE
		Update  HOGIADINH set MAHOGD = @MAHOGD, TENCHUHO  = @TENCHUHO, SOCMND = @SOCMND, SOLUONGTV = @SOLUONGTV where  MAHOGD = @MAHOGD
if (@@ERROR <> 0)
ROLLBACK TRANSACTION
else
COMMIT TRANSACTION


CREATE PROCEDURE psTimHoGiaDinh @MAHOGD NVARCHAR (10)
AS
BEGIN TRANSACTION
	select * from HOGIADINH WHERE MAHOGD = @MAHOGD
if (@@ERROR <> 0)
ROLLBACK TRANSACTION
else
COMMIT TRANSACTION


CREATE PROCEDURE psHienThiHoGiaDinh 
AS
BEGIN TRANSACTION
	select * from HOGIADINH 
if (@@ERROR <> 0)
ROLLBACK TRANSACTION
else
COMMIT TRANSACTION