USE quanlychungcu


create procedure psThongKeTienNuoc @THANG int, @NAM int
as
begin transaction
	select b.MACTHDNUOC, TENHOADON, MANHANVIEN, MAHOGD, MACANHO, NGAYIN, SOLUONG, DONGIA, TONGTIEN
	from HOADONNUOC a, CTHDNUOC b
	where a.MAHOADONNUOC = b.MAHOADONNUOC and MONTH(NGAYIN) = @THANG and YEAR(NGAYIN) = @NAM
if (@@ERROR <> 0)
ROLLBACK TRANSACTION
else
COMMIT TRANSACTION

create procedure psThongKeTienNuocTheoNam @NAM int
as
begin transaction
	select b.MACTHDNUOC, TENHOADON, MANHANVIEN, MAHOGD, MACANHO, NGAYIN, SOLUONG, DONGIA, TONGTIEN
	from HOADONNUOC a, CTHDNUOC b
	where a.MAHOADONNUOC = b.MAHOADONNUOC and YEAR(NGAYIN) = @NAM
if (@@ERROR <> 0)
ROLLBACK TRANSACTION
else
COMMIT TRANSACTION