USE quanlychungcu

create procedure psThongKeCanHo @TRANGTHAI NVARCHAR(30)
as
begin transaction
	select b.MACANHO, TENCANHO, LOAICANHO, TRANGTHAI, GIACANHO, b.MAKHU, THOIHAN, GIATRI, TONGTIEN
	from KHU a, CANHO b, HOPDONGGD c, CTHOPDONGGD d
	where a.MAKHU = b.MAKHU and b.MACANHO = c.MACANHO and c.MAHOPDONG = d.MAHOPDONG and TRANGTHAI = @TRANGTHAI
if (@@ERROR <> 0)
ROLLBACK TRANSACTION
else
COMMIT TRANSACTION



