USE quanlychungcu

create procedure psThongKeTienDien @THANG int, @NAM int
as
begin transaction
	select b.MACTHDDIEN, TENHOADON, MANHANVIEN, MAHOGD, MACANHO, NGAYIN, SOLUONG, DONGIA, TONGTIEN
	from HOADONDIEN a, CTHDDIEN b
	where a.MAHOADONDIEN = b.MAHOADONDIEN and MONTH(NGAYIN) = @THANG and YEAR(NGAYIN) = @NAM
if (@@ERROR <> 0)
ROLLBACK TRANSACTION
else
COMMIT TRANSACTION

create procedure psThongKeTienDienTheoNam @NAM int
as
begin transaction
	select b.MACTHDDIEN, TENHOADON, MANHANVIEN, MAHOGD, MACANHO, NGAYIN, SOLUONG, DONGIA, TONGTIEN
	from HOADONDIEN a, CTHDDIEN b
	where a.MAHOADONDIEN = b.MAHOADONDIEN and YEAR(NGAYIN) = @NAM
if (@@ERROR <> 0)
ROLLBACK TRANSACTION
else
COMMIT TRANSACTION